const IDENTIFIER = '[home]';

export const FETCH_CONTACTS_REQUEST = `${IDENTIFIER}FETCH_CONTACTS_REQUEST`;
export const FETCH_CONTACTS_SUCCESS = `${IDENTIFIER}FETCH_CONTACTS_SUCCESS`;
export const FETCH_CONTACTS_FAILURE = `${IDENTIFIER}FETCH_CONTACTS_FAILURE`;
