const IDENTIFIER = '[contact]';

export const TOGGLE_CONTACT_PHONES = `${IDENTIFIER}TOGGLE_CONTACT_PHONES`;

export const DELETE_CONTACT = `${IDENTIFIER}DELETE_CONTACT`;

export const ADD_CONTACT = `${IDENTIFIER}ADD_CONTACT`;

export const UPDATE_CONTACT = `${IDENTIFIER}UPDATE_CONTACT`;